// city_timezones.dart

Map<String, String> cityTimeZones = {
  'Seoul': 'Asia/Seoul',
  'Tokyo': 'Asia/Tokyo',
  'New York': 'America/New_York',
  'Los Angeles': 'America/Los_Angeles',
  'London': 'Europe/London',
  'Paris': 'Europe/Paris',
  'Beijing': 'Asia/Shanghai',
  'Mumbai': 'Asia/Kolkata',
  'Sydney': 'Australia/Sydney',
  'Amsterdam': 'Europe/Amsterdam',
  'Athens': 'Europe/Athens',
  'Barcelona': 'Europe/Madrid',
  'Berlin': 'Europe/Berlin',
  'Brussels': 'Europe/Brussels',
  'Budapest': 'Europe/Budapest',
  'Copenhagen': 'Europe/Copenhagen',
  'Dublin': 'Europe/Dublin',
  'Helsinki': 'Europe/Helsinki',
  'Istanbul': 'Europe/Istanbul',
  'Lisbon': 'Europe/Lisbon', 
  'Madrid': 'Europe/Madrid',
  'Manchester': 'Europe/London',
  'Milan': 'Europe/Rome',
  'Munich': 'Europe/Berlin',
  'Oslo': 'Europe/Oslo',  
  'Prague': 'Europe/Prague',
  'Rome': 'Europe/Rome',
  'Stockholm': 'Europe/Stockholm',
  'Vienna': 'Europe/Vienna',
  'Warsaw': 'Europe/Warsaw',
  'Zurich': 'Europe/Zurich',
  'Calgary': 'America/Edmonton',
  'Edmonton': 'America/Edmonton',
  'Halifax': 'America/Halifax',
  'Hamilton': 'America/Toronto',
  'Kelowna': 'America/Vancouver',  
  'Montreal': 'America/Montreal',
  'Ottawa': 'America/Toronto',
  'Quebec City': 'America/Montreal',
  'Regina': 'America/Regina',
  'Saskatoon': 'America/Regina',
  'St. John\'s': 'America/St_Johns',
  'Toronto': 'America/Toronto',
  'Vancouver': 'America/Vancouver',
  'Victoria': 'America/Vancouver',
  'Winnipeg': 'America/Winnipeg',
  // Add more cities here
};